name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: telegram_task_db
        ports:
          - 5432:5432
        options: --health-cmd='pg_isready -U user' --health-timeout=30s --health-start-period=10s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker image to Docker Hub (optional)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag telegram-task-bot-bot:latest yourdockerhubusername/telegram-task-bot:latest
          docker push yourdockerhubusername/telegram-task-bot:latest
